<?php include("head.php"); ?>
<?php include_once("analyticstracking.php") ?>

	<div id="splash">
		<img src="img/splash-publications_bw.jpg">
		<div id="splash-inner">
			<h2>Publications</h2>
		</div>
	</div>
	<div id="content" class="break">
		<div id="content-inner">
			<a class="pdf" href="pdf/pub4.pdf">PDF</a>
			<a href="http://onlinelibrary.wiley.com/doi/10.1002/2015WR017395/full"><h2>Coupled surface-subsurface hydrologic measurements reveal <br />infiltration, recharge, and discharge dynamics across the <br />swash zone of a sandy beach</h2></a> 
			
			<h3><b>James W. Heiss</b>, Jack A. Puleo, and Holly A. Michael (2015)<br />
<i>Water Resources Research</i>, doi:10.1002/2015WR017395.</h3>
			<p>Swash-groundwater interactions affect the biogeochemistry of beach aquifers and the transport of solutes and sediment across the beachface. Improved understanding of the complex, coupled dynamics of surface and subsurface flow processes in the swash zone is required to better estimate chemical fluxes to the sea and predict the morphological evolution of beaches. Simultaneous high-frequency measurements of saturation, water table elevation, and the cross-shore locations of runup and the boundary between the saturated and unsaturated beachface (surface saturation boundary) were collected on a sandy beach to link groundwater flow dynamics with swash zone forcing. Saturation and lysimeter measurements showed the dynamic response of subsurface saturation to swash events and permitted estimation of infiltration rates. Surface and subsurface observations revealed a decoupling of the surface saturation boundary and the intersection between the water table and the beachface. Surface measurements alone were insufficient to delineate the infiltration and discharge zones, which moved independently of the surface saturation boundary. Results show for the first time the motion and areal extent of infiltration and recharge zones, and constrain the maximum size of the subaerial discharge zone over swash and tidal time scales. The width of the infiltration zone was controlled by swash processes and subaerial discharge was controlled primarily by tidal processes. These dynamics reveal the tightly coupled nature of surface and subsurface processes over multiple timescales, with implications for sediment transport and fluid and solute fluxes through the hydrologically and biogeochemically active intertidal zone of sandy beaches. This article is protected by copyright. All rights reserved.</p>
			<h4><b>Heiss, J. W.</b>, J.A. Puleo, and H.A. Michael (2015), Coupled surface-subsurface hydrologic measurements reveal infiltration, recharge, and discharge dynamics across the swash zone of a sandy beach, Water Resources Research, doi:10.1002/2015WR017395.</h4>
		</div>
	</div>
		<div id="content" class="break">
		<div id="content-inner">
			<a class="pdf" href="pdf/pub3.pdf">PDF</a>
			<a href="http://onlinelibrary.wiley.com/doi/10.1002/lno.10029/full"><h2>Dynamic hydrologic and biogeochemical processes drive microbially <br />enhanced iron and sulfur cycling within the intertidal mixing zone <br />of a beach aquifer</h2></a> 
			
			<h3>Sean M. McAllister, Joshua M. Barnett, <b>James W. Heiss</b>, Alyssa J. Findlay,<br /> Daniel J. MacDonald, Charles L. Dow, George W. Luther, Holly A. Michael, Clara S. Chan (2015)<br />
<i>Limnology and Oceanography</i>, 60(1), 329-245, doi:10.1002/lno.10029.</h3>
			<p>Intertidal aquifers host a reactive zone comprised of Fe mineral-coated sands where fresh and saline groundwaters mix. This zone may significantly influence the export of C, N, P, Fe, and other metals in submarine groundwater discharge (SGD). Toward determining the roles of microbes in Fe and S mineralization, and the interplay of microbiology with geochemistry and physical hydrology, we conducted a biogeochemical study of pore waters at Cape Shores, Delaware. Here, fresh groundwater provides Fe(II), which precipitates as FeIIIOOH predominantly through microbial Fe(II) oxidation. Candidate division OP3 was the dominant microbial group associated with Fe(II)- and Fe(III)-rich regions of the aquifer, suggesting that this uncharacterized phylum may be involved in Fe(II) oxidation. Saline water brings O2, sulfate, and organic C into the intertidal mixing zone. Microbial reduction of sulfate produces sulfide that is transported to the Fe-mineralized zone leading to the transformation of FeOOH to Fe(II) sulfides. Microbial populations are structured by the availability of chemical species supplied along groundwater flow paths. Seasonal changes in the relative supply of fresh and saline groundwater affect solute fluxes, and therefore, microbial controls on the location and composition of the Fe-mineralized zone. Ultimately, the composition, extent, and dynamics of the Fe-mineralized zone will affect the sequestration, affinity, and residence time of solutes bound for export to coastal oceans through SGD.</p>
			<h4>McAllister, S. M., Barnett, J. M., <b>Heiss, J. W.</b>, Findlay, A. J., MacDonald, D. J., Dow, C. L., Luther, G. W., Michael, H. A. and Chan, C. S. (2015), Dynamic hydrologic and biogeochemical processes drive microbially enhanced iron and sulfur cycling within the intertidal mixing zone of a beach aquifer, Limnology and Oceanography, doi:10.1002/lno.10029.</h4>
		</div>
	</div>
		<div id="content" class="break">
		<div id="content-inner">
			<a class="pdf" href="pdf/pub2.pdf">PDF</a>
			<a href="http://onlinelibrary.wiley.com/doi/10.1002/2014WR015574/full"><h2>Saltwater-freshwater mixing dynamics in a sandy beach aquifer <br/>over tidal, spring-neap, and seasonal cycles</h2></a> 
			
			<h3><b>James W. Heiss</b> and Holly A. Michael (2014)<br/>
<i>Water Resources Research</i>, doi:10.<i>1002</i>/2014WR015574.</h3>
			<p>The biogeochemical reactivity of sandy beach aquifers is closely linked to physical flow and solute transport processes. Thus, a clearer understanding of the hydrodynamics in the intertidal zone is needed to accurately estimate chemical fluxes to the marine environment. A field and numerical modeling study was conducted over a one-year timeframe to investigate the combined effects of tidal stage, spring-neap variability in tidal amplitude, and seasonal inland water table oscillations on intertidal salinity and flow dynamics within a tide-dominated micro-tidal sandy beach aquifer. Measured and simulated salinities revealed an intertidal saline circulation cell with a structure and cross-sectional mixing zone area that varied over tidal, spring-neap and seasonal timescales. The size of the circulation cell and area of the mixing zone were shown for the first time to be most affected by seasonal water table oscillations, followed by tidal amplitude and tidal stage. The intertidal circulation cell expanded horizontally and vertically as the inland water table declined, displacing the fresh discharge zone and lower interface seaward. Over monthly spring-neap cycles, the center of the circulation cell shifted from beneath the backshore and upper beachface to the base of the beach. Salinity variations in the intertidal zone over semidiurnal tidal cycles were minimal. The dynamics of the circulation cell were similar in simulations with and without a berm. The highly transient nature of intertidal salinity over multiple time scales may have important implications for the types and rates of chemical transformations that occur in groundwater prior to discharge to the ocean.</p>
			<h4>Heiss, J. W. and H. A. Michael (2014), Saltwater-freshwater mixing dynamics in a sandy beach aquifer on tidal, spring-neap, and seasonal cycles, <i>Water Resources Research</i>, doi:10.<i>1002</i>/2014WR015574.</h4>
		</div>
	</div>
	<div id="content" class="break">
		<div id="content-inner">
			<a class="pdf" href="pdf/pub1.pdf">PDF</a>
			<a href="http://www.sciencedirect.com/science/article/pii/S0272771414000638"><h2>Swash zone moisture dynamics and unsaturated infiltration <br/>in two sandy beach aquifers</h2></a> 
			
			
			<h3><b>James W. Heiss</b>, William J. Ullman, Holly A. Michael (2014)<br/>
<i>Estuarine, Coastal and Shelf Science</i>, 143, 20-31, doi:10.1016/j.ecss.2014.03.015.</h3>
			<p>The intertidal zone of coastal aquifers is a dynamic region of mixing between saline surface water and fresh groundwater. Groundwater circulation in this zone is affected by complex forcing mechanisms that operate on a range of timescales and can regulate chemical fluxes to marine environments.We evaluated wave swash-induced infiltration and associated flow dynamics in the unsaturated region of two sandy beach aquifers with differing wave conditions and beach morphologies. Moisture and pressure sensors were used to measure fluctuations in water content, water table elevation, and hydraulic gradients at high frequencies (5 Hz) in the swash zone at mean lower low water, mean sea level, and mean higher high water. Water content in the unsaturated region of the swash zone responded to wave overtopping and swash infiltration, with a rapid rise in water content followed by a slower decline. Swash-induced unsaturated infiltration rates, calculated from water content response, were lowest near low tide and increased up the beachface with inflow highest near high tide at both sites, consistent with an increase in water table depth up the beach. Unsaturated infiltration was 1.6 m3/m per tidal cycle at the wave- dominated beach and 0.4 m3/m per tidal cycle at the tide-dominated beach. Saturated pore pressure measurements show that a water table mound formed as a consequence of swash infiltration that migrated up the beach during rising tide, leading to divergent seaward/landward groundwater flow. The results demonstrate the significant and spatially variable effects of wave swash on moisture dynamics in the unsaturated zone of beach aquifers, and show that these effects depend on wave conditions and beach characteristics. Results have implications for understanding transport and reaction of solutes in this biogeochemically active zone.</p>
			<h4>Heiss, J. W., W.J. Ullman, and H.A. Michael (2014), Swash zone moisture dynamics and unsaturated infiltration in two sandy beach aquifers, <i>Estuarine, Coastal and Shelf Science</i>, 143, 20-31. doi:10.1016/j.ecss.2014.03.015.</h4>
		</div>
	</div>
	<div id="content" class="break">
		<div id="content-inner">
			<a class="pdf" href="pdf/SWIM.pdf">PDF</a>
			<h2>Tidal, spring-neap, and seasonal dynamics of a saltwater-freshwater <br/>mixing zone in a beach aquifer</h2>
			<h3><b>James W. Heiss</b> and Holly A. Michael<br/>
Proceedings of the 23rd Salt Water Intrusion Meeting, pp.159-161</h3>
			<p>The fate of chemicals discharging to the marine environment through submarine groundwater discharge may be influenced by physical flow and transport processes in the beach aquifer. A more comprehensive understanding of beach hydrodynamics over a range of time scales will thus aid in more accurately estimating chemical fluxes to coastal surface waters. The combined effects of tidal stage, tidal amplitude, and seasonal upland water table oscillations on the salinity distribution and flow dynamics in a tide-dominated sandy beach were investigated over one year using field measurements and variable-density numerical modeling. Measured and simulated results revealed an intertidal saline circulation cell with a structure and cross-sectional mixing zone area that varied over tidal, spring-neap, and seasonal time scales. Seasonal upland water table oscillations were the most important factor controlling the size of the mixing zone, followed by tidal amplitude and tidal stage. The size of the circulation cell expanded as the upland water table declined. The expansion of the cell displaced the fresh discharge zone and offshore interface seaward. The saltwater circulation cell shifted from below the upper beachface to the low tide mark in response to a change in tidal amplitude over a spring-neap cycle. Tidal stage had minimal effect on the salinity distribution in the intertidal zone over a semidiurnal tidal cycle. Seasonal variation of mean sea level did not appear to influence intertidal salinity. Salinity measurements one day following Hurricane Sandy suggest that the beach aquifer adjusted quickly after a moderate storm surge and enhanced terrestrial fresh groundwater inflow from rainfall. The highly transient nature of beach aquifer salinity over multiple time scales may have important implications for the types and rates of chemical transformations that occur in groundwater prior to discharge to the ocean.</p>
			<h4>Heiss, J. W., and H. A. Michael. (2014), Tidal, spring-neap, and seasonal dynamics of a saltwater-freshwater mixing zone in a beach aquifer, In: <i>Proceedings of the 23rd Salt Water Intrusion Meeting</i>, June 16-21, Husum, Germany.</h4>
		</div>
	</div>
	<div id="content">
		<div id="content-inner">
			<h2>Intertidal mixing zone dynamics and swash-induced<br/> infiltration in a sandy beach aquifer, Cape Henlopen, Delaware</h2>
			<h3><b>James W. Heiss</b> (2011)<br/>
Master's Thesis, University of Delaware Department of Geological Sciences </h3>
			<p>Submarine groundwater discharge has been shown to be an important source of nutrients, heavy metals, and organic compounds to the coastal ocean. Physical flow and mixing dynamics in the intertidal zone may influence these contaminant fluxes; however the mechanisms that contribute to the spatial and temporal dynamics of mixing of saltwater and through-flowing freshwater are not well understood. Flow systems in two shallow beach aquifers at Cape Henlopen, DE were characterized over multiple time scales using multilevel porewater samplers, pressure transducers, and moisture sensors. Porewater samples indicate the presence of a saline groundwater circulation cell beneath the beachface that is formed by seawater infiltrating across the upper beachface, which then circulates downward and seaward before discharging farther offshore. The circulation cell deepens and its areal extent increases when forced with a larger tidal amplitude. Longer term monitoring shows that higher inland water tables during spring and the resultant increase in freshwater forcing cause the circulation cell to freshen while lower inland water tables associated with winter result in a well-developed density inversion.</p>
<p>A study of swash-induced infiltration was performed to quantify the effects of swash zone width and tidal elevation on the flux of seawater into the beach aquifer. High-frequency pressure and soil moisture measurements from shore-perpendicular arrays across the beachface were used to infer influx rates. Direct measurement of moisture content in the unsaturated zone and capillary fringe is needed to infer fluxes due to moisture conditions above the water table that are not measured by the pressure sensors. Infiltration occurred during the rising tide at the leading edge of the swash zone and increased in magnitude from low tide to high tide. Infiltration rates were on average 2.2 times greater near mean higher high water than near mean lower low water. Measurements revealed that swash zone width influences infiltration: influx rates associated with a beach with a wider swash zone were 2.7 times higher than those of a beach with a narrower swash zone. These insights into beach groundwater dynamics have implications for estimating fluid and chemical fluxes to coastal waters.</p>
			<h4>Heiss, J.W. (2011), Intertidal mixing zone dynamics and swash induced infiltration in a sandy beach aquifer, Cape Henlopen, Delaware, M.S. Thesis, University of Delaware, 99 pp.</h4>
		</div>
	</div>

<?php include("foot.php"); ?>

